### ISSUE TITLE
Remove cyclic dependency with dcrd repo

### ISSUE THREAD

**Issue by jrick** [decred/dcrutil#64]
Any packages from this repo that depend on dcrd that dcrd is also importing need to be moved into the dcrd repo.  This prevents a cyclic repo dependency structure.

The following packages/code from this repo do not need to be moved to dcrd (but some will need to be moved to their own repos):

* ~~base58 (after removing the dependency on chainhash)~~ moved to github.com/decred/base58
* ~~coinset ([nothing public imports this package](https://godoc.org/github.com/decred/dcrutil/coinset?importers) and the code can be nuked completely)~~ removed in #65
* ~~dcrutil (TLS certificate generation does not depend on dcrd)~~ moved to dcrd in decred/dcrd#879

Any packages that remain that depend on dcrd packages can stay in this repo, but it is important that the rest which do not import dcrd (but which dcrd imports) are moved to their own repos, or else the cycle will remain.

These packages/code do need to be moved to the dcrd repo:

* bloom (imports dcrd packages and is required by dcrd)
* hdkeychain (import many dcrd packages and dcrd imports it for the rpc test harness)
* dcrutil (Address, Amount, Block, Hash160, Tx, and WIF all cause cyclic dependencies with dcrd)

**Comment by davecgh** [comment]
The bit about bloom filters is not true.  There is code for bloom filters in dcrd including serving them and the ability to disable them.

**Comment by jrick** [comment]
fixed

**Comment by jrick** [comment]
Since there are far fewer items that need to be moved into dcrd than those that do not, I plan on splitting the base58 package, TLS certificate generation, and WIF private key decoding/encoding to their own packages.  The base58 and TLS code will need to be moved to their own repos, since dcrd depends on them.  The WIF code can either be in its own repo or moved to dcrwallet.  Suggestions welcome.

**Comment by davecgh** [comment]
I think WIF can be moved into wallet as a package.  It's definitely only related to wallet.

As far as the certificate generation stuff, I'm torn on whether to put them it in its own repo or to just make it a package in dcrd.  I imagine everything that uses it probably already depends on dcrd anyways, and it seems pointless to have an entire repo for a single function that could easily just be copied into relevant code anyways.

**Comment by jrick** [comment]
I missed something during my initial analysis.

We need to decide where the AppDataDir function will be moved to.  It has no direct dependencies on dcrd, so it could either be moved to the dcrd repo (where?), its own repo (what?), or into another repo (what/where?).

**Comment by jrick** [comment]
Decided to just move it into dcrd/dcrutil.  Not a fan of the lazy util package idea but trying to avoid as much churn as possible.  Would love to revisit the util package in a future PR.

**Comment by jrick** [comment]
The WIF code needs to live in dcrd as well.  It is imported by rpcclient, which has since moved to a dcrd package.  I will keep it under the github.com/decred/dcrd/dcrutil package.

**Comment by davecgh** [comment]
Resolved by decred/dcrd#888 and #67.
